### ISSUE TITLE
Immersive Engineering Epic Shader Bags drop directly from bosses rather than going into the boss drop chests

### ISSUE THREAD

**Issue by Toastr125** [TeamTwilight/twilightforest#1786]
### Forge Version

43.2.7

### Twilight Forest Version

4.2.1518

### Steps to Reproduce

1. Play with both Twilight Forest and Immersive Engineering
2. Kill a Twilight Forest boss

### What You Expected

The Epic Shader Bag would be in the boss drop chest

### What Happened Instead

It dropped from the boss as an item

### Additional Details

It makes some sense that it would work that way given that the boss chests are kind of a special thing, but I remember back in 1.12 when the bosses dropped special shaders, the Knight Phantom and Ur-Ghast ones would be in their chests rather than dropping directly.
In a similar vein, the Knight Phantoms now drop one shader bag each, so you get 6 from killing all of them. I don't think it's worth making a separate ticket for this since the issues are closely related (and fixing the one this ticket is made for would fix this issue as well), so I'm just including it here.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Tamaized** [comment]
Do we even have control over that

**Comment by GizmoTheMoonPig** [comment]
our bosses shouldnt even be dropping the epic shader bags to begin with, we just dont tag them in the base mod since compat is being split off into its own mod. 
I dont know how IE adds the shader bags to mob loot, but if theyre using the drop event rather than a loot modifier I dont think we can do anything about it

**Comment by GizmoTheMoonPig** [comment]
ok yeah they use the event, we're not able to do anything about it https://github.com/BluSunrize/ImmersiveEngineering/blob/1.19.2/src/main/java/blusunrize/immersiveengineering/common/EventHandler.java#L237-L247
Gonna close this as its not really fixable

**Comment by GizmoTheMoonPig** [comment]
worth noting that when I get around to finishing the IE compat mod this wont be an issue. I use loot modifiers to add our shader bags to the loot so they will always drop into the chests. They also get excluded from dropping the shaders there as well
